
    exception = rescue (ArgumentError) do
      method_with_keyword_arguments_with_mandatory_argument
    end
  print exception.ArguementError
  
